<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=$this->e($title)?></title>

    <?php foreach ($css as $cssFile): ?>
        <link rel="stylesheet" href="/assets/css/<?=$cssFile?>">
    <?php endforeach ?>

    <?php foreach ($js as $jsFile): ?>
        <script defer src="/assets/js/<?=$jsFile?>"></script>
    <?php endforeach ?>

</head>
<body>
    <?php if (!empty($notices)): ?>
        <?php foreach ($notices as $notice) : ?>
            <?php $this->insert('toasts::notice', [ 'notice' => $notice ]) ?>
        <?php endforeach ?>
    <?php endif ?>

    <?php $this->insert('shared::footer') ?>
