<select
    class="form-select"
    name="<?=$this->e($name)?>"
    id="<?=$this->e($name)?>_input"
    placeholder="<?=$this->e($field['display'])?>"
>

    <?php foreach ($field['setList'] as $option): ?>
        <option value="<?=$this->e($option)?>">
            <?=$this->e($option, 'ucwords')?>
        </option>
    <?php endforeach ?>

</select>
<label for="<?=$this->e($name)?>_input">
    <?=$this->e($field['display'])?>
</label>