<input
    type="text"
    class="form-control form-control-sm"

    id="<?=$this->e($name)?>_input"
    name="<?=$this->e($name)?>"
    placeholder="<?=$this->e($field['display'])?>"

    <?php if (!empty($field['maxLength'])): ?>
        maxlength="<?=$this->e($field['maxLength'])?>"
    <?php endif ?>

    <?php if (!empty($field['required'])): ?>
        required
    <?php endif ?>
>
<label for="<?=$this->e($name)?>_input">
    <?=$this->e($field['display'])?>
</label>