<?php $this->layout('layouts::page') ?>

<div class="row">
    <?php foreach ($events as $event): ?>
        <div class="col-2">
            <div class="card">
                <div class="m-2">
                    <?= $this->e($event->getId()) ?>
                </div>
                <div class="m-2">
                    <?= $this->e($event->getUserId()) ?>
                </div>
                <div class="m-2">
                    <?= $this->e($event->getEventTypeId()) ?>
                </div>
                <div class="m-2">
                    <?= $this->e($event->getDescription()) ?>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>