<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/img/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/img/favicon/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">

    <title><?=$this->e($title)?></title>

    <?php foreach ($css as $cssFile): ?>
        <link rel="stylesheet" href="/assets/css/<?=$cssFile?>.css">
    <?php endforeach ?>

</head>
<body class="min-vh-100 min-vw-100 overflow-hidden">

    <?php if (!empty($notices)): ?>
        <?php foreach ($notices as $notice) : ?>
            <?php $this->insert('toasts::notice', [ 'notice' => $notice ]) ?>
        <?php endforeach ?>
    <?php endif ?>