<nav class="sidebar">
    <a href="/" class="sidebar-title mb-md-0 me-md-auto">
        <span class="fs-4">Metis</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <?php foreach ([
            [ 'title' => 'Dashboard', 'icon' => '' ],
            [ 'title' => 'Events', 'icon' => '' ]
        ] as $page) : ?>
            <li class="nav-item">
                <a href="/<?= $this->e($page['title'], 'strtolower') ?>" class="nav-link" aria-current="page">
                    <?= $this->e($page['icon']) ?>
                    <?= $this->e($page['title']) ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
</nav>