<div class="toast position-absolute top-0 start-50 translate-middle-x align-items-center text-white bg-<?= $notice->getStatus() ?> border-0 mt-2" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="d-flex">
        <div class="toast-body">
            <?php if (!empty($notice->getIcon())): ?>
                <?= $notice->getIcon() ?>
            <?php endif ?>
            <?= $notice->getMessage() ?>
        </div>
        <div class="d-flex ms-auto">
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button>
            <button type="button" class="btn shadow-none" data-bs-toggle="collapse" data-bs-target="#notice-info">
                <i class="fas fa-expand"></i>
            </button>
        </div>
    </div>
    <div class="collapse" id="notice-info">
        <div class="notice-info p-2">
            <?= $notice->getLine() ?> @ <?= $notice->getFile() ?>
        </div>
    </div>
</div>